version: '3.0'

services:
    main:
        build:
            context: .
        env_file:
            - .env
        volumes:
            - .:/app
            - /app/node_modules
        ports:
            - "${APP_PORT}:${APP_PORT}"
        command: npm run start:dev
        depends_on:
            - db
        restart: always
    db:
        image: postgres:12
        environment:
            PG_DATA: /var/lib/postgresql/data
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        ports:
            - 5433:5432
        volumes:
            - dbdata:/var/lib/postgresql/data
        restart: always

volumes:
    dbdata:
